import std/os
let root = currentSourcePath().parentDir().parentDir()
switch("path", root / "src")
switch("path", root / "players" / "baseline")
if projectName() == "baseline_wasm":
  let sdk = getEnv("WASI_SDK_PATH")
  if sdk.len == 0: quit("Set WASI_SDK_PATH to wasi-sdk 33", 1)
  switch("os", "linux")
  switch("cpu", "wasm32")
  switch("cc", "clang")
  switch("clang.exe", sdk / "bin/clang")
  switch("clang.linkerexe", sdk / "bin/clang")
  switch("threads", "off")
  switch("mm", "arc")
  switch("exceptions", "goto")
  switch("define", "release")
  switch("define", "noSignalHandler")
  switch("define", "useMalloc")
  switch("define", "artlogNoCurl")
  switch("define", "arenaComponent")
  switch("noMain", "on")
  switch("passL", "-mexec-model=reactor")
  for name in ["paintbot_init", "paintbot_buffer", "paintbot_step", "paintbot_output_size"]:
    switch("passL", "-Wl,--export=" & name)
  switch("out", root / "singlepod/baseline.wasm")
